Send only updated files to S3 syriaca-front-end

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,35 +37,35 @@ jobs:
       # Step 3: Files to S3
 
       # # Option 1: Upload only changed files to S3
-      # - name: Get list of changed files
-      #   id: changes
-      #   run: |
-      #     git fetch origin main
-      #     git diff --name-only HEAD^ HEAD > changed_files.txt
-      #     cat changed_files.txt
+      - name: Get list of changed files
+        id: changes
+        run: |
+          git fetch origin main
+          git diff --name-only HEAD^ HEAD > changed_files.txt
+          cat changed_files.txt
 
-      # - name: Sync changed files in S3
-      #   if: success()
-      #   run: |
-      #     while read file; do
-      #       echo "Attempting to upload $file..."
-      #       if ! aws s3 cp "$file" "s3://gaddel-syriaca-front-end/$file" ; then
-      #         echo "File $file not found. Falling back to sync for deletion handling."
-      #         aws s3 sync ./ s3://gaddel-syriaca-front-end --delete --exact-timestamps --exclude "json-data/*" --exclude "testHtml/*" --exclude "person/*" --exclude "place/*" --exclude "keyword/*" --exclude "cbss/*" --exclude "subject/*" --exclude "work/*"
-      #         break  # Stop further uploads and rely on sync
-      #       fi
-      #     done < changed_files.txt
-      #   env:
-      #     AWS_REGION: ${{ secrets.AWS_REGION }}
-      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  
+      - name: Sync changed files in S3
+        if: success()
+        run: |
+          while read file; do
+            echo "Attempting to upload $file..."
+            if ! aws s3 cp "$file" "s3://srophe-syriaca-front-end/$file" ; then
+              echo "File $file not found. Falling back to sync for deletion handling."
+              aws s3 sync ./ s3://srophe-syriaca-front-end --delete --exact-timestamps --exclude "json-data/*" --exclude "testHtml/*" --exclude "person/*" --exclude "place/*" --exclude "keyword/*" --exclude "cbss/*" --exclude "subject/*" --exclude "work/*"
+              break  # Stop further uploads and rely on sync
+            fi
+          done < changed_files.txt
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  
 
       # Option 2: Full redeployment
 
-      - name: Debug
-        run: aws s3 sync ./ s3://gaddel-syriaca-front-end --delete --exact-timestamps --dryrun
-      - name: Sync all files to S3
-        run: |
-          aws s3 sync ./ s3://gaddel-syriaca-front-end --delete --exact-timestamps --exclude "json-data/*" --exclude "testHtml/*" --exclude "person/*" --exclude "place/*" --exclude "keyword/*" --exclude "cbss/*" --exclude "subject/*" --exclude "work/*"
-        env:
-          AWS_REGION: ${{ secrets.AWS_REGION }}
-          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+      # - name: Debug
+      #   run: aws s3 sync ./ s3://gaddel-syriaca-front-end --delete --exact-timestamps --dryrun
+      # - name: Sync all files to S3
+      #   run: |
+      #     aws s3 sync ./ s3://gaddel-syriaca-front-end --delete --exact-timestamps --exclude "json-data/*" --exclude "testHtml/*" --exclude "person/*" --exclude "place/*" --exclude "keyword/*" --exclude "cbss/*" --exclude "subject/*" --exclude "work/*"
+      #   env:
+      #     AWS_REGION: ${{ secrets.AWS_REGION }}
+      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
